// Generated on the ${date} by Play!
package controllers;

import play.*;
import play.mvc.*;

<#assign classbody>
/**
${pojo.getClassJavaDoc(pojo.getDeclarationName()+"s generated by Play!", 0)}
 */
<#if secure?if_exists>
@With(Secure.class)
</#if>
public class ${pojo.getDeclarationName() + "s"} extends CRUD {}
</#assign>
${classbody}
